[LEVEL_LOCKED]
ENG = "Level locked"
#_CHI = 
#_CHT = 
#_CZE = 
#_DUT = 
#_FRE = 
#_GER = 
#_ITA = 
#_JPN = 
#_KOR = 
#_LAT = 
#_POL = 
#_POR = 
#_RUS = 
#_SPA = 
#_SWE = 
#_UKR = 

[LEVEL_NOT_BEATEN]
ENG = "Level not beaten"
#_CHI = 
#_CHT = 
#_CZE = 
#_DUT = 
#_FRE = 
#_GER = 
#_ITA = 
#_JPN = 
#_KOR = 
#_LAT = 
#_POL = 
#_POR = 
#_RUS = 
#_SPA = 
#_SWE = 
#_UKR = 

[LEVEL_BEATEN]
ENG = "Level beaten!"
#_CHI = 
#_CHT = 
#_CZE = 
#_DUT = 
#_FRE = 
#_GER = 
#_ITA = 
#_JPN = 
#_KOR = 
#_LAT = 
#_POL = 
#_POR = 
#_RUS = 
#_SPA = 
#_SWE = 
#_UKR = 

[FLAME_UNLOCKED]
ENG = "Unlocked"
#_CHI = 
#_CHT = 
#_CZE = 
#_DUT = 
#_FRE = 
#_GER = 
#_ITA = 
#_JPN = 
#_KOR = 
#_LAT = 
#_POL = 
#_POR = 
#_RUS = 
#_SPA = 
#_SWE = 
#_UKR = 

[FLAME_ACTIVATED]
ENG = "Activated"
#_CHI = 
#_CHT = 
#_CZE = 
#_DUT = 
#_FRE = 
#_GER = 
#_ITA = 
#_JPN = 
#_KOR = 
#_LAT = 
#_POL = 
#_POR = 
#_RUS = 
#_SPA = 
#_SWE = 
#_UKR = 

[FLAME_ACHIEVED]
ENG = "Achieved"
#_CHI = 
#_CHT = 
#_CZE = 
#_DUT = 
#_FRE = 
#_GER = 
#_ITA = 
#_JPN = 
#_KOR = 
#_LAT = 
#_POL = 
#_POR = 
#_RUS = 
#_SPA = 
#_SWE = 
#_UKR = 

[RECIPE_IMPS]
ENG = "Cheaper Imps"
#_CHI = 
#_CHT = 
#_CZE = 
#_DUT = 
#_FRE = 
#_GER = 
#_ITA = 
#_JPN = 
#_KOR = 
#_LAT = 
#_POL = 
#_POR = 
#_RUS = 
#_SPA = 
#_SWE = 
#_UKR = 

[RECIPE_RESEARCH]
ENG = "Complete Research"
#_CHI = 
#_CHT = 
#_CZE = 
#_DUT = 
#_FRE = 
#_GER = 
#_ITA = 
#_JPN = 
#_KOR = 
#_LAT = 
#_POL = 
#_POR = 
#_RUS = 
#_SPA = 
#_SWE = 
#_UKR = 

[RECIPE_MANUFACTURE]
ENG = "Complete Manufacturing"
#_CHI = 
#_CHT = 
#_CZE = 
#_DUT = 
#_FRE = 
#_GER = 
#_ITA = 
#_JPN = 
#_KOR = 
#_LAT = 
#_POL = 
#_POR = 
#_RUS = 
#_SPA = 
#_SWE = 
#_UKR = 

[RECIPE_KILL CHICKENS]
ENG = "Kill chickens"
#_CHI = 
#_CHT = 
#_CZE = 
#_DUT = 
#_FRE = 
#_GER = 
#_ITA = 
#_JPN = 
#_KOR = 
#_LAT = 
#_POL = 
#_POR = 
#_RUS = 
#_SPA = 
#_SWE = 
#_UKR = 